### ISSUE TITLE
Imprecise exception display

### ISSUE THREAD

**Issue by DoomTaper** [owtf/ptp#14]
Although ptp handles precise exceptions but it doesn't show that
e.g.
`ptp=PTP('w3af')`
`ptp.parse('some/random/non-existing/directory')`

Below error is shown
`Traceback (most recent call last):
  File "testing.py", line 3, in <module>
    c = ptp.parse('/root/Desktop/w3af_repo')
  File "/root/Desktop/ptp/ptp/ptp.py", line 121, in parse
    raise NotSupportedToolError('This tool is not supported by PTP.')
ptp.libptp.exceptions.NotSupportedToolError: This tool is not supported by PTP.`

while it should display why the error occurred like above it should show directory doesn't exists or something related to it, helps in correcting error for user itself.

**Comment by DePierre** [comment]
@DoomTaper how about the following errors?

```pytb
>>> from ptp import PTP
>>> p = PTP('w3af')
>>> p.parse()
No parser matched `ToolParser((), {})`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ptp/ptp.py", line 122, in parse
    raise NotSupportedToolError('This tool is not supported by PTP.')
ptp.libptp.exceptions.NotSupportedToolError: This tool is not supported by PTP.
>>> p.parse('foo/bar')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ptp/ptp.py", line 119, in parse
    self._init_parser(*args, **kwargs)
  File "ptp/ptp.py", line 94, in _init_parser
    if parser.is_mine(*args, **kwargs):
  File "ptp/tools/w3af/parser.py", line 66, in is_mine
    stream = cls.handle_file(pathname, filename, first=first)
  File "ptp/libptp/parser.py", line 178, in handle_file
    raise IOError("Report matching '%s' cannot be found." % os.path.join(pathname, filename))
IOError: Report matching 'foo/bar/*.xml' cannot be found.
```

**Comment by DoomTaper** [comment]
@DePierre exactly what I was looking for :)

**Comment by DePierre** [comment]
Re-opened via https://github.com/owtf/ptp/commit/9760a1f46ced8fa310a2071f953c7e4c96118be9#diff-329faea9e46f3af8da40d4c54f4b00ffR106

**Comment by viyatb** [comment]
Closing as stale (>90 days inactive). Reopen is welcome after updating context and confirming this is still in scope.
