### ISSUE TITLE
PTP auto-detection feature broken

### ISSUE THREAD

**Issue by DePierre** [owtf/ptp#16]
As @DoomTaper pointed out, the fix for #14 broke PTP's auto-detection feature:

``` pytb
Python 2.7.12+ (default, Aug  4 2016, 20:04:34) 
[GCC 6.1.1 20160724] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ptp import PTP
>>> a = PTP()
>>> a.parse('/tmp/test/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ptp/ptp.py", line 119, in parse
    self._init_parser(*args, **kwargs)
  File "ptp/ptp.py", line 94, in _init_parser
    if parser.is_mine(*args, **kwargs):
  File "ptp/tools/wapiti/parser.py", line 52, in is_mine
    stream = cls.handle_file(pathname, filename, first=first)
  File "ptp/libptp/parser.py", line 178, in handle_file
    raise IOError("Report matching '%s' cannot be found." % os.path.join(pathname, filename))
IOError: Report matching '/tmp/test/*.xml' cannot be found.
>>> 

```

**Comment by DePierre** [comment]
Fixed in https://github.com/owtf/ptp/commit/9760a1f46ced8fa310a2071f953c7e4c96118be9#diff-329faea9e46f3af8da40d4c54f4b00ffR106, which re-opens #14 for discussion.
